# Generated by Django 5.0.6 on 2024-07-05 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def default_user():
    # TODO: improve this with conditions or beforeupdate.
    return 1


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default=default_user(), on_delete=django.db.models.deletion.CASCADE,
                                    related_name='vehicles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
